# https://www.josean.com/posts/tmux-setup

# set -g default-terminal "screen-256color"

# Set the default terminal to a 256-color-aware one
set-option -g default-terminal "tmux-256color"

# Enable True Color (24-bit) passthrough
set-option -g terminal-overrides ",xterm*:Tc"

# unable to change prefix
# set -g prefix C-f
# unbind C-b
# bind-key C-f send-prefix


# split window
unbind %
bind v split-window -h -c "#{pane_current_path}"        # -c "..." added so that the new pane opens with the cwd

unbind '"'
bind V split-window -v -c "#{pane_current_path}"        # -c "..." added so that the new pane opens with the cwd

# new window
unbind c
bind c new-window -c "#{pane_current_path}"             # -c "..." added so that the new window opens with the cwd


# source config file (does not work, need to do C-b I reload)
unbind r
bind r source-file ~/.tmux.conf


# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# maximize or restore pane
bind -r m resize-pane -Z


# enable mouse
set -g mouse on


# vim mode in copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection    # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection     # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane                # don't exit copy mode after dragging with mouse


# status bar
#+--- Bars ---+
# Set background to black
set -g status-bg black
set -g status-fg white

# Left side: Session Name
set -g status-left-length 40
set -g status-left "#[fg=black,bg=blue,bold] #S @ #H "

# Right side: Date | Time | User
set -g status-right-length 150
set -g status-right "#[fg=white,bg=brightblack] %Y-%m-%d | %H:%M:%S #[fg=default,bg=default] #[fg=black,bg=cyan,bold] #(whoami) #[fg=black,bold]#{?client_prefix,#[reverse] PREFIX #[noreverse],}"

#+--- Windows ---+
# Center the window list
set -g status-justify centre

# Inactive window
set -g window-status-format "#[fg=white,bg=brightblack] #I.#P : #W #F "
set -g window-status-separator ""

# Active window
set -g window-status-current-format "#[fg=black,bg=cyan,bold] #I.#P : #W (#{pane_current_command}) #F "

# --- Window Activity ---
# Set a different color for windows with activity
set -g window-status-activity-style bg=red,fg=black
